#!/bin/bash
#
# Script name: blockhosts
#
# UnlockMe: Customize, tweak and clean your system
# https://github.com/ralphys/unlockme/
#
# Created by Ralphy Rhdez <rafaelrhd3z@gmail.com>
# Website - https://unlockforus.com
#
# Blacklisy sources based on StevenBlack hosts list. 
# See https://github.com/StevenBlack/hosts 
#
# Expectation: These unified hosts files should serve all devices, regardless of OS.

_APPNAME="Blacklist Generator"
dialog0="\n${_APPNAME} is running unprivileged
\nYou won't be able to apply the resulting blacklist to
the system; you'll be prompted to save it instead.\n"

if [[ $EUID != 0 ]]; then

	yad --window-icon="gtk-dialog-info" --image=gtk-dialog-info --borders="8" --title="$_APPNAME" --text="$dialog0" --on-top \
		--fixed --button="Authenticate"\!gtk-refresh:2 --button="gtk-cancel":1 --button="Continue"\!gtk-ok:0 2>/dev/null
	
	case "$?" in
		0) : ;;
		2) pkexec $0; exit 0 ;;
		*) exit 0 ;;
	esac
else 
	if [[ -f "/etc/NetworkManager/dnsmasq.d/blacklist" ]]; then
		zenity --question --width="300" --height="120" --title="Active blacklist found" \
			   --text="\nAn active blacklist is currently enable in the system. Would you like to remove it?" 2>/dev/null

		if [[ "$?" = "0" ]]; then 
		
			echo "# Removing active blacklist..." 
			rm -f "/etc/NetworkManager/dnsmasq.d/blacklist" ; sleep 2
			echo "# Restarting Network Manager..." 
			service network-manager restart ; sleep 3
			echo "# Blacklist removed." && sleep 1 
												  
			continue
		fi
	fi
fi

(
TMPFILE="/tmp/blacklist.process" 				# temporary blacklist file
GENFILEB="/tmp/blacklist.custom" 				# custom config
[[ ! -e "$GENFILEB" ]] && touch "$GENFILEB"
GENFILEW="/tmp/whitelist.custom" 				# custom config
[[ ! -e "$GENFILEW" ]] && touch "$GENFILEW"
bgenfile="/tmp/blacklist.conf"
[[ -e "$bgenfile" ]] && rm -f "$bgenfile"

clean_up() {
	rm -f $TMPFILE $GENFILEB $GENFILEW $bgenfile
}

# function Save generated file 
save_file() {

	szSavePath=$(zenity --file-selection --title=" Save Generated file" --width="550" --height="380" \
						--filename="${HOME}/blacklist.conf" --window-icon="$_ICON" --file-filter='*.conf' \
                        --file-filter='All files | *' --save --confirm-overwrite 2>/dev/null)
    if [[ "${PIPESTATUS}" != "0" ]]; then 
    	clean_up; exit 0
    fi
    if [[ "$?" = "0" ]]; then
    	mv "$bgenfile" "$szSavePath"; clean_up
    fi
}

gen_blacklist() {

echo "10"
echo "# Processing sources..." ; sleep .5

SOURCES=""
SOURCES="$@"

# Blacklist additional sites
BLACKLIST="$(< $GENFILEB)"

# Whitelist additional sites
WHITELIST="$(< $GENFILEW)"

echo "20"
echo "# Starting Source lists download..." ; sleep 1
until ping -q -c1 google.com >/dev/null; do
	echo "# Waiting for an internet connection..."
	sleep 3
done

echo "30"
echo "# Downloading selected Source lists..."
echo -n "" > "$TMPFILE"

for s in ${SOURCES}; do
	{ (wget $s -O - || logger "Failed: $s") | tr -d "\r" | sed -e '/^[[:alnum:]:]/!d' | awk '{print $2}' | sed -e '/^localhost$/d' >> $TMPFILE
} & done

wait

sleep 3

echo "40"
echo "# Verifying download..." ; sleep .5

if [[ -s "$TMPFILE" ]]; then sleep 1
	echo "50"
	echo "# Success: Download completed" ; sleep .7
else
	echo " Failed: Download unsuccessful, aborting... :("
	rm -f "$TMPFILE" "$GENFILEB" "$GENFILEW" > /dev/null
	exit 1
fi

echo "60"
echo "# Generating blacklist.conf file...." ; sleep .7

for b in ${BLACKLIST}; do
	echo "$b" >> "$TMPFILE"
done

echo "70"
echo "# Adding custom blacklist records... done" ; sleep .5

for w in ${WHITELIST}; do
	sed -i -e "/$w/d" "$TMPFILE"
done

echo "80"
echo "# Adding custom whitelist records... done" ; sleep .5

sed -i -e "/0\.0\.0\.0/d" "$TMPFILE"

# unbound formatting 
if [[ "$_DNSSERV" == "UNBOUND" ]]; then
	echo "85"
	echo "# Configuring records for unbound..."
	sort -u "$TMPFILE" -o "$TMPFILE"

	cat "$TMPFILE" | awk '{print "local-zone: \""$1"\" redirect\nlocal-data: \""$1" A 0.0.0.0\""}' > "$bgenfile" ; sleep 2
fi

# dnsmasq formatting
if [[ "$_DNSSERV" == "DNSMASQ" ]]; then
	echo "85"
	echo "# Configuring records for dnsmasq..." 

	sort -u "$TMPFILE" -o "$TMPFILE"

	cat "$TMPFILE" | awk '{print "address=/"$0"/0.0.0.0/"}' > "$bgenfile" ; sleep 2

	# clean list errors in domain names - e.g.: domain..net instead of domain.net
		echo "90"
		echo "# Cleaning up records. Please wait..."
		grep -q -F '..' "$bgenfile" && sed -i '/\.\./d' "$bgenfile" ; sleep 1
		
	# delete address=/0.0.0.0/ if in blacklist
		echo "95"
		grep -q -Fx 'address=/0.0.0.0/' "$bgenfile" && sed -i '/address=\/\0\.0\.0\.0\//d' "$bgenfile" ; sleep 1
		echo "96"
		grep -q -Fx 'address=//0.0.0.0/' "$bgenfile" && sed -i '/address=\/\/\0\.0\.0\.0\//d' "$bgenfile" ; sleep 1

	# cleanup incompleted TLDs
		echo "98"
		grep -q -Fx 'address=/.com/0.0.0.0/' "$bgenfile" && sed -i '/address=\/\.com\/\0\.0\.0\.0\//d' "$bgenfile" ; sleep 1
		no_tld=$(rev $bgenfile | cut -c9- | rev | cut -d\= -f2 | sed -n '/\./!p')
		
		for tld in ${no_tld}; do
			echo "# Cleaning wrong TLD record ${tld}..." ; sleep .5
			sed -i "$tld"'d' "$bgenfile"
		done
fi

echo "99"
echo "# File generated, $(wc -l < $bgenfile) unique hosts to block\n\n -- Custom blocked hosts: $(wc -w < $GENFILEB)\n -- Custom allowed hosts: $(wc -w < $GENFILEW)\n" ; sleep 3

fail_dialog="<b> Don't panic</b>. Your internet connectivity failed after applying the generated blacklist. \
This is usually caused by errors in one or more additional lists that $_APPNAME could not properly sanitize.\n
All changes will be reverted. Please try again selecting fewer additional lists."
 
if [[ "$_DNSSERV" == "UNBOUND" ]] || [[ "$EUID" != 0 && "$_DNSSERV" == "DNSMASQ" ]]; then
	save_file
else
	cp "$bgenfile" /etc/NetworkManager/dnsmasq.d/blacklist ; clean_up
	echo "# Adding blacklist to the system..." ; sleep 1
	echo "# Restarting Network Manager..." 
	service network-manager stop && service network-manager start ; sleep 2

	let COUNT=0
	until ping -q -c1 google.com >/dev/null
	do
    	echo "# Waiting for Network Manager to restart..."
    	sleep 3
    	let COUNT=COUNT+1
    if (( $COUNT == "3" )); then
    	echo "# Internet not reachable..."
    	zenity --error --width="340" --height="160" --title="Oppss, something went wrong" --text="$fail_dialog" 2>/dev/null
 
			echo "# Removing active blacklist..." 
			rm -f "/etc/NetworkManager/dnsmasq.d/blacklist" ; sleep 2
			echo "# Restarting Network Manager..." 
			service network-manager stop && service network-manager start ; sleep 3
			echo "# Blacklist removed." ; sleep 1 
												 
        exit 1
    fi
	done

	echo "# Blacklist applied." ; sleep 2
fi
echo "100"
}

# start here - Select DNS Service
echo "1"
_RUN_ICON="/usr/share/unlockme/icons/ui/run.png"
if which unbound > /dev/null; then

	echo "# Select DNS Service. Waiting for user input..." ; sleep .1

	SELECT=$(zenity --forms --width="360" --height="130" --title=" $_APPNAME" --text="" --ok-label=" Go" --cancel-label="Quit" \
				    --add-combo " Select DNS Service:" --combo-values "dnsmasq|unbound" 2>/dev/null)

	if [[ "$SELECT" =~ "unbound" ]]; then _DNSSERV="UNBOUND"
	elif [[ "$SELECT" =~ "dnsmasq" ]]; then _DNSSERV="DNSMASQ"
	else exit 0
	fi
else
	 _DNSSERV="DNSMASQ"
fi

# Unified hosts based on StevenBlack hosts list. See https://github.com/StevenBlack/hosts
# Unified hosts variables
unified="https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"																			# Unified hosts = (adware + malware)
unified_fakenews="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts" 											# Unified hosts + fakenews
unified_gambling="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling/hosts" 											# Unified hosts + gambling
unified_porn="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts"														# Unified hosts + porn
unified_social="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/social/hosts"													# Unified hosts + social
unified_fakenews_gambling="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts"							# Unified hosts + fakenews + gambling
unified_fakenews_porn="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-porn/hosts"									# Unified hosts + fakenews + porn
unified_fakenews_social="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-social/hosts"								# Unified hosts + fakenews + social
unified_gambling_porn="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling-porn/hosts"									# Unified hosts + gambling + porn
unified_gambling_social="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling-social/hosts"								# Unified hosts + gambling + social
unified_porn_social="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn-social/hosts"										# Unified hosts + porn + social
unified_fakenews_gambling_porn="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts"					# Unified hosts + fakenews + gambling + porn
unified_fakenews_gambling_social="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-social/hosts"				# Unified hosts + fakenews + gambling + social
unified_fakenews_porn_social="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-porn-social/hosts"						# Unified hosts + fakenews + porn + social
unified_gambling_porn_social="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling-porn-social/hosts" 					# Unified hosts + gambling + porn + social
unified_fakenews_gambling_porn_social="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts"	# Unified hosts + fakenews + gambling + porn + social

# Unified hosts selector dialog
_dialog="$_APPNAME consolidates several reputable hosts files and merges them into a unified list with duplicates removed.\n
	<span font='9'>⚫ Lists source: StevenBlack's @github hosts list
	⚫ Unified hosts includes known adware + malware hosts\n</span>"

# unified hosts selector dialog
_wlimage="/usr/share/unlockme/icons/ui/whitelist90.png"
_dialog2="\n<span font='12'>  Additional Hosts List\n</span>
  <span font='9'>⚫ Multiple lists can be selected</span>"

echo "5"
echo "# Selecting Unified blacklist sources..." ; sleep .2

ans=$(yad --list --radiolist --width="580" --height="580" --title=" $_APPNAME" --text="$_dialog" --window-icon="$_RUN_ICON" \
		  --image="$_wlimage" --image-on-top --separator=" " --wrap --borders="8" --button="gtk-cancel":1 --button="Next":0 \
		  --hide-column="2" --print-column="2" --column="▼" --column="blist" --column="Select Unified hosts list" \
	TRUE  "$unified" "  Unified hosts" \
	FALSE "$unified_fakenews" "  Unified hosts + Fake News" \
	FALSE "$unified_gambling" "  Unified hosts + Gambling" \
	FALSE "$unified_porn" "  Unified hosts + porn" \
	FALSE "$unified_social" "  Unified hosts + Social" \
	FALSE "$unified_fakenews_gambling" "  Unified hosts + Fakenews + Gambling" \
	FALSE "$unified_fakenews_porn" "  Unified hosts + Fakenews + Porn" \
	FALSE "$unified_fakenews_social" "  Unified hosts + Fakenews + Social" \
	FALSE "$unified_gambling_porn" "  Unified hosts + Gambling + Porn" \
	FALSE "$unified_gambling_social" "  Unified hosts + Gambling + Social" \
	FALSE "$unified_porn_social" "  Unified hosts + Porn + Social" \
	FALSE "$unified_fakenews_gambling_porn" "  Unified hosts + Fakenews + Gambling + Porn" \
	FALSE "$unified_fakenews_gambling_social" "  Unified hosts + Fakenews + Gambling + Social" \
	FALSE "$unified_fakenews_porn_social" "  Unified hosts + Fakenews + Porn + Social" \
	FALSE "$unified_gambling_porn_social" "  Unified hosts + Gambling + Porn + Social" \
	FALSE "$unified_fakenews_gambling_porn_social" "  Unified hosts + fakenews + gambling + porn + social" 2>/dev/null)

if [[ "${PIPESTATUS}" != "0" ]]; then clean_up ; exit 0 ; fi

# Additional hosts based on StevenBlack hosts list. See https://github.com/StevenBlack/hosts
# additional hosts variables
add2="https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts"
add16="https://hosts-file.net/ad_servers.txt"
add11="https://raw.githubusercontent.com/FadeMind/hosts.extras/master/Spotify-Ad-free/hosts"
add12="https://raw.githubusercontent.com/StevenBlack/hosts/master/data/StevenBlack/hosts"
add13="https://raw.githubusercontent.com/tyzbit/hosts/master/data/tyzbit/hosts"

echo "10"
echo "# Selecting additional blacklist sources..."

# additional hosts selector dialog yad --selectable-labels
ans2=$(yad --list --checklist --width="600" --height="300" --title=" $_APPNAME" --text="$_dialog2" --window-icon="$_RUN_ICON" \
		   --borders="8" --button="gtk-cancel":1 --button="Next":0 --image="$_wlimage" --hide-column="2" --separator=" " \
		   --print-column="2" --column="▼" --column="blist" --column="List Name" --column="Description" \
			FALSE "$add2" "add.2o7Net" "Tracking sites based on hostsfile.org content" \
			FALSE "$add16" "hpHosts" "Ads and Tracking servers only by hosts-file.net" \
			FALSE "$add11" "SpotifyAds" "Sources based on Xeroday @github content" \
			FALSE "$add12" "Steven Black's ad-hoc " "Additional sketchy domains by StevenBlack @github" \
			FALSE "$add13" "tyzbit" "Microsoft tracking domains by tyzbit @github" 2>/dev/null)

if [[ "${PIPESTATUS}" != "0" ]]; then clean_up ; exit 0 ; fi

# Whitelist domains manually
echo "15"
echo "# Whitelisting domains..."
_dialog3="\nUse this option to whitelist domains you do not want to block. \
\n\nFor example, you could\'ve opted to block Unified hosts + Social \
but you want to allow facebook.com by adding it here so that it \
isn't blocked.\n\n
▼ Whitelist domains (space separated)"

szwhite=$(yad --entry --image="$_wlimage" --button="gtk-cancel:1" --button="Next":0 --title=" Whitelist Domains" --wrap \
			  --text="$_dialog3" --entry-text="" --width="540" --height="300" --borders="8" --center --window-icon="$_RUN_ICON" 2>/dev/null)
	
	if [[ "${PIPESTATUS}" != "0" ]]; then clean_up ; exit 0 ; fi
	echo "$szwhite" > "$GENFILEW"

echo "20"
echo "# Blackisting domains..."
_dialog4="\nBlacklist additional domains not listed in source lists. \
\n\nFor example, you could\'ve opted to block Unified hosts + Social \
but you also want to block yahoo.com and youtube.com by adding them here.\n\n
▼ Blacklist domains (space separated)"

szblack=$(yad --entry --image="/usr/share/unlockme/icons/ui/blacklist90.png" --button="gtk-cancel:1" --button="Next":0 --title=" Blacklist Domains" \
			  --text="$_dialog4" --entry-text="" --width="540" --height="300" --borders="8" --center --window-icon="$_RUN_ICON" --wrap 2>/dev/null)
	
	if [[ "${PIPESTATUS}" != "0" ]]; then clean_up ; exit 0; fi
	echo "$szblack" > "$GENFILEB"

# Begin blacklist processing
gen_blacklist $ans $ans2 ) | yad --progress --width="340" --height="110" --title="Progress Status" --text="" --center --no-buttons --skip-taskbar \
								 --undecorated --no-cancel --percentage=0 --auto-close --auto-kill 2>/dev/null
(( $? != 0 )) && zenity --error --text="Error in command execution."
exit 0

