#!/bin/bash
## With love from Ralphy - https://unlockforus.com

#######################################################################################
## SOURCES based on StevenBlack hosts list. See https://github.com/StevenBlack/hosts ##
#######################################################################################

# Expectation: These unified hosts files should serve all devices, regardless of OS.

_APPNAME=" Blacklist Generator"
dialog0="\n${_APPNAME} is running unprivileged
\nYou won't be able to apply the resulting blacklist to
the system; you'll be prompted to save it instead.\n"

if [ $EUID -ne 0 ]; then

	yad --window-icon="gtk-dialog-info" --image=gtk-dialog-info --borders=8 --title="$_APPNAME" --text="$dialog0" --on-top \
		--fixed --button="gtk-quit":1 --button="Authenticate"\!gtk-refresh:2 --button="Continue"\!gtk-ok:0
	
	case "$?" in
		0) : ;;
		2) pkexec $0; exit 0 ;;
		*) exit 0 ;;
	esac
else :
fi

if [ $EUID -eq 0 ]; then
	if [ -f "/etc/NetworkManager/dnsmasq.d/blacklist" ]; then
		zenity --question --width="370" --height="120" --title="Active blacklist found" \
			   --text="\nAn active blacklist is currently enable in the system.\nWould you like to remove it?" 2>/dev/null

		if [[ "$?" -eq "0" ]]; then 
			(
			echo "# Removing active blacklist..." 
			rm -f "/etc/NetworkManager/dnsmasq.d/blacklist" && sleep 2
			echo "# Restarting Network Manager..." 
			service network-manager restart ; sleep 3
			echo "# Blacklist removed." && sleep 1 ) | yad --progress --pulsate --width=340 --height=110 --title="Progress Status" --text="" --center --no-buttons \
														   --skip-taskbar --undecorated --no-cancel --percentage=0 --auto-close --auto-kill
			exit 0
		else :
		fi
	fi
fi

(
TMPFILE="/tmp/blacklist.process" ## temporary blacklist file
GENFILEB="/tmp/blacklist.custom" ## custom config
[ ! -e "$GENFILEB" ] && touch "$GENFILEB"
GENFILEW="/tmp/whitelist.custom" ## custom config
[ ! -e "$GENFILEW" ] && touch "$GENFILEW"
bgenfile="/tmp/blacklist.conf"
[ -e "$bgenfile" ] && rm -f "$bgenfile"

clean_up() {
	rm -f $TMPFILE $GENFILEB $GENFILEW $bgenfile
}

# function Save generated file 
save_file() {
	szSavePath=$(zenity --title=" Save Generated file" --width="550" --height="380" --file-selection --filename="$HOME/blacklist.conf" \
                              --window-icon="$_ICON" --file-filter='*.conf' --file-filter='All files | *' --save --confirm-overwrite 2>/dev/null)
    if [ "${PIPESTATUS}" -ne "0" ]; then clean_up; exit 0; fi
    if [ "$?" -eq "0" ]; then mv "$bgenfile" "$szSavePath"; clean_up ; fi
}

gen_blacklist() {

echo "10"
echo "# Processing sources..." ; sleep .5

SOURCES=""
SOURCES="$@"

# Blacklist additional sites (add inside quotes, space-separated)
# BLACKLIST="google-analytics.com bbtrack.com yldbt.com switchadhub.com mathtag.com adnxs.com ads.revjet.com"
BLACKLIST="$(cat $GENFILEB)"
#echo "$BLACKLIST" > $GENFILEB

WHITELIST="$(cat $GENFILEW)"

echo "20"
echo "# Starting Source lists download..." ; sleep 1
until ping -q -c1 google.com >/dev/null; do
	echo "# Waiting for an internet connection..."
	sleep 3
done

echo "30"
echo "# Downloading selected Source lists..."
echo -n "" > "$TMPFILE"
for s in $SOURCES; do
{ (wget $s -O - || logger "Failed: $s") | tr -d "\r" | sed -e '/^[[:alnum:]:]/!d' | awk '{print $2}' | sed -e '/^localhost$/d' >> $TMPFILE
} & done

wait

sleep 3

echo "40"
echo "# Verifying download..." ; sleep .5

if [ -s "$TMPFILE" ]; then sleep 1
	echo "50"
	echo "# Success: Download completed" ; sleep .7
else
	echo " Failed: Download unsuccessful, aborting... :("
	rm -f $TMPFILE $GENFILEB $GENFILEW > /dev/null
	exit 1
fi

echo "60"
echo "# Generating blacklist.conf file...." ; sleep .7

for b in $BLACKLIST; do
	echo "$b" >> $TMPFILE
done
echo "70"
echo "# Adding custom blacklist records... done" ; sleep .5

for w in $WHITELIST; do
	sed -i -e "/$w/d" $TMPFILE
done
echo "80"
echo "# Adding custom whitelist records... done" ; sleep .5

sed -i -e "/0\.0\.0\.0/d" $TMPFILE

if [[ "$_DNSSERV" == "UNBOUND" ]]; then
	echo "90"
	echo "# Configuring records for unbound..." ; sleep 1
	sort -u $TMPFILE -o $TMPFILE
	cat $TMPFILE | awk '{print "local-zone: \""$1"\" redirect\nlocal-data: \""$1" A 0.0.0.0\""}' > "$bgenfile"
fi


if [[ "$_DNSSERV" == "DNSMASQ" ]]; then
	echo "90"
	echo "# Configuring records for dnsmasq..." ; sleep 1

sort -u $TMPFILE -o $TMPFILE
cat $TMPFILE | awk '{print "address=/"$0"/0.0.0.0/"}' > "$bgenfile"
fi

echo "99"
echo "# File generated, $(wc -l < $bgenfile) unique hosts to block\n\n -- Custom blocked hosts: $(wc -w < $GENFILEB)\n -- Custom allowed hosts: $(wc -w < $GENFILEW)\n" ; sleep 3
 
if [[ "$_DNSSERV" == "UNBOUND" ]] || [ $EUID -ne 0 ] && [[ "$_DNSSERV" == "DNSMASQ" ]]; then save_file
else
	cp "$bgenfile" /etc/NetworkManager/dnsmasq.d/blacklist ; clean_up
	echo "# Adding blacklist to the system..." && sleep 1
	echo "# Restarting Network Manager..." 
	service network-manager restart ; sleep 3
	echo "# Blacklist applied." && sleep 1
fi
echo "100"
}

# start here - Select DNS Service
echo "1"
_RUN_ICON="/usr/share/unlockme/icons/ui/run.png"
if which unbound > /dev/null; then

	echo "# Select DNS Service. Waiting for user input..." ; sleep .1

	SELECT=$(zenity --forms --width="360" --height="130" --title=" $_APPNAME" --text="" --ok-label=" Go" --cancel-label="Quit" \
				    --add-combo " Select DNS Service:" --combo-values "dnsmasq|unbound" 2>/dev/null)

	if [[ "$SELECT" =~ "unbound" ]]; then _DNSSERV="UNBOUND"
	elif [[ "$SELECT" =~ "dnsmasq" ]]; then _DNSSERV="DNSMASQ"
	else exit 0
	fi
else
	 _DNSSERV="DNSMASQ"
fi

# Unified hosts based on StevenBlack hosts list. See https://github.com/StevenBlack/hosts
# Unified hosts variables
unified="https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"																			# Unified hosts = (adware + malware)
unified_fakenews="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews/hosts" 											# Unified hosts + fakenews
unified_gambling="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling/hosts" 											# Unified hosts + gambling
unified_porn="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn/hosts"														# Unified hosts + porn
unified_social="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/social/hosts"													# Unified hosts + social
unified_fakenews_gambling="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts"							# Unified hosts + fakenews + gambling
unified_fakenews_porn="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-porn/hosts"									# Unified hosts + fakenews + porn
unified_fakenews_social="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-social/hosts"								# Unified hosts + fakenews + social
unified_gambling_porn="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling-porn/hosts"									# Unified hosts + gambling + porn
unified_gambling_social="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling-social/hosts"								# Unified hosts + gambling + social
unified_porn_social="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/porn-social/hosts"										# Unified hosts + porn + social
unified_fakenews_gambling_porn="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts"					# Unified hosts + fakenews + gambling + porn
unified_fakenews_gambling_social="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-social/hosts"				# Unified hosts + fakenews + gambling + social
unified_fakenews_porn_social="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-porn-social/hosts"						# Unified hosts + fakenews + porn + social
unified_gambling_porn_social="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/gambling-porn-social/hosts" 					# Unified hosts + gambling + porn + social
unified_fakenews_gambling_porn_social="https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts"	# Unified hosts + fakenews + gambling + porn + social

# Unified hosts selector dialog
_dialog="Sources based on StevenBlack @github hosts list
\n  ⚫ Unified hosts includes known adware + malware hosts\n"

# additional hosts selector dialog
_dialog2="Sources based on StevenBlack @github hosts list 
\n  ⚫ Additional hosts lists - Multiple can be selected"

echo "5"
echo "# Selecting Unified blacklist sources..." && sleep .1

ans=$(zenity  --list --width="480" --height="540" --ok-label="Next" --title=" Blacklist Generator" --text="$_dialog" --window-icon="$_RUN_ICON" \
			  --radiolist --hide-column="2" --print-column="2" --column="" --column="blist" --column="Blacklist Source" \
TRUE  "$unified" "Unified hosts" \
FALSE "$unified_fakenews" "Unified hosts + Fake News" \
FALSE "$unified_gambling" "Unified hosts + Gambling" \
FALSE "$unified_porn" "Unified hosts + porn" \
FALSE "$unified_social" "Unified hosts + Social" \
FALSE "$unified_fakenews_gambling" "Unified hosts + Fakenews + Gambling" \
FALSE "$unified_fakenews_porn" "Unified hosts + Fakenews + Porn" \
FALSE "$unified_fakenews_social" "Unified hosts + Fakenews + Social" \
FALSE "$unified_gambling_porn" "Unified hosts + Gambling + Porn" \
FALSE "$unified_gambling_social" "Unified hosts + Gambling + Social" \
FALSE "$unified_porn_social" "Unified hosts + Porn + Social" \
FALSE "$unified_fakenews_gambling_porn" "Unified hosts + Fakenews + Gambling + Porn" \
FALSE "$unified_fakenews_gambling_social" "Unified hosts + Fakenews + Gambling + Social" \
FALSE "$unified_fakenews_porn_social" "Unified hosts + Fakenews + Porn + Social" \
FALSE "$unified_gambling_porn_social" "Unified hosts + Gambling + Porn + Social" \
FALSE "$unified_fakenews_gambling_porn_social" "Unified hosts + fakenews + gambling + porn + social" 2>/dev/null)
if [ "${PIPESTATUS}" -ne "0" ]; then clean_up ; exit 0 ; fi

# Additional hosts based on StevenBlack hosts list. See https://github.com/StevenBlack/hosts
# additional hosts variables
add2="https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts"
# add6="https://raw.githubusercontent.com/mitchellkrogza/Badd-Boyz-Hosts/master/hosts" # (issues when selected with other lists)
add11="https://raw.githubusercontent.com/FadeMind/hosts.extras/master/SpotifyAds/hosts"
add12="https://raw.githubusercontent.com/StevenBlack/hosts/master/data/StevenBlack/hosts"
add13="https://raw.githubusercontent.com/tyzbit/hosts/master/data/tyzbit/hosts"
add16="http://hosts-file.net/ad_servers.asp"


echo "10"
echo "# Selecting additional blacklist sources..."
# additional hosts selector dialog yad --selectable-labels
ans2=$(zenity --list --checklist --width="600" --height="300" --ok-label="Next" --title=" $_APPNAME" --text="$_dialog2" --window-icon="$_RUN_ICON" \
			   --hide-column="2" --separator=" " --print-column="2" --column="" --column="blist" --column="List Name" --column="Description" \
		FALSE "$add2" "add.2o7Net" "Tracking sites based on hostsfile.org content" \
		FALSE "$add11" "SpotifyAds" "Sources based on Xeroday @github content" \
		FALSE "$add12" "Steven Black's ad-hoc list  " "Additional sketchy domains" \
		FALSE "$add13" "tyzbit" "Microsoft tracking domains" \
		FALSE "$add16" "hpHosts" "Ads and Tracking servers only" 2>/dev/null)

if [ "${PIPESTATUS}" -ne "0" ]; then clean_up ; exit 0 ; fi

# Whitelist domains manually
echo "15"
echo "# Whitelisting domains..."
_dialog3="Use this option to whitelist domains you do not want to block.\n
For example, you could\'ve opted to block Unified hosts + Social
but you want to allow facebook.com by adding it here so that it
isn't blocked.\n\n
▼ Whitelist domains (space separated)"

szwhite=$(yad --entry --image="/usr/share/unlockme/icons/ui/whitelist90.png" --button="gtk-cancel:1" --button="Next":0 --title=" Whitelist Domains" \
			  --text="$_dialog3" --entry-text="" --width=500 --height=300 --borders=8 --fixed --center --window-icon="$_RUN_ICON")
	if [ "${PIPESTATUS}" -ne "0" ]; then clean_up ; exit 0 ; fi
	echo "$szwhite" > "$GENFILEW"

echo "20"
echo "# Blackisting domains..."
_dialog4="Blacklist additional domains not listed in source lists.\n
For example, you could\'ve opted to block Unified hosts + Social
but you also want to block yahoo.com and youtube.com by adding\nthem here.\n\n
▼ Blacklist domains (space separated)"

szblack=$(yad --entry --image="/usr/share/unlockme/icons/ui/blacklist90.png" --button="gtk-cancel:1" --button="Next":0 --title=" Blacklist Domains" \
			  --text="$_dialog4" --entry-text="" --width=500 --height=300 --borders=8 --fixed --center --window-icon="$_RUN_ICON")
	if [ "${PIPESTATUS}" -ne "0" ]; then clean_up ; exit 0; fi
	echo "$szblack" > "$GENFILEB"

# Begin blacklist processing
gen_blacklist $ans $ans2 ) | yad --progress --width=340 --height=110 --title="Progress Status" --text="" --center --no-buttons --skip-taskbar \
								 --undecorated --no-cancel --percentage=0 --auto-close --auto-kill 2>/dev/null
(( $? != 0 )) && zenity --error --text="Error in zenity command."
exit 0

