#!/bin/bash
# NAME:         get_download
# AUTHOR:       (c) 2014 Glutanimate
# DESCRIPTION:  graphical frontend to wget in form of a yad script
# FEATURES:     - display progress of multiple simultaneous downloads
#               - set maximum number of simultaneous downloads
# DEPENDENCIES: yad
#
#               Install yad on Ubuntu with:
#
#                   sudo add-apt-repository ppa:webupd8team/y-ppa-manager
#                   sudo apt-get update
#                   sudo apt-get install yad
#
# LICENSE:      GNU GPLv3 (http://www.gnu.de/documents/gpl-3.0.en.html)
#
# USAGE:        get_download <space-delimited URLs>
#               Closing the yad dialog will terminate all downloads in progress
#

# Variables and settings

# locale
export LANG=C
export LANG=C.UTF-8

URILIST="$@"  # gets list of URIs from stdin
MAXDLS="5"    # set maximum number of simultaneous downloads
USAGE="$0 <space-delimited URLs>"
userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"

# Usage checks

if [[ -z "$URILIST" ]]
  then
      echo "Error: No arguments provided"
      echo "Usage: $USAGE"
      exit 1
fi

# download file and extract progress, speed and ETA from wget
# we use sed regex for this
# source: http://ubuntuforums.org/showthread.php?t=306515&page=2&p=7455412#post7455412
# modified to work with different locales and decimal point conventions
GET_FILE_DL() {
    wget -c -T5 -t2 -U "$userAgent" "$1" 2>&1 | sed -u \
    "s/.* \([0-9]\+%\)\ \+\([0-9,.]\+.\) \(.*\)/$2:\1\n$2:# Downloading at \2\/s, ETA \3/"
    RET_WGET="${PIPESTATUS[0]}"             # get return code of wget
    if [[ "$RET_WGET" = "0" ]]                # check return code for errors
      then
          echo "$2:100%"
          echo "$2:#Download completed."
          exit 0
      else
          echo "$2:#Download error."
          exit 1
    fi
}

# compose list of bars for yad
for URI in ${URILIST}; do                     # iterate through all URIs
    FILENAME="${URI##*/}"                   # extract last field of URI as filename
    YADBARS="$YADBARS --bar=:NORM"          # add filename to the list of URIs
done

IFS=" "
COUNTER="1"
DYNAMIC_COUNTER="1"

# Set GUI variables up
TITLE="UnlockMe - Downloading..."                 # dialog title
TEXT="\n<b>Download</b> in progress:\n- ${FILENAME}\n" # dialog text
ICON="emblem-downloads"                     # window icon (appears in launcher)
IMAGE="browser-download"                    # window image (appears in dialog)

# main
# iterate through all URIs, download them in the background and 
# pipe all output simultaneously to yad
# source: http://pastebin.com/yBL2wjaY

for URI in ${URILIST}; do
    if [[ "$DYNAMIC_COUNTER" = "$MAXDLS" ]] # only download n files at a time
      then
          GET_FILE_DL "$URI" "$COUNTER"     # if limit reached wait until wget complete
          DYNAMIC_COUNTER="1"               # before proceeding (by not sending download() to bg)
      else
          GET_FILE_DL "$URI" "$COUNTER" &   # pass URI and URI number to download()
          DYNAMIC_COUNTER="$[$DYNAMIC_COUNTER+1]"
    fi
    COUNTER="$[$COUNTER+1]"                 # increment counter
done | yad --multi-progress --fixed --image-on-top --borders="8" --width="440" --height="170" --auto-kill --auto-close \
           --button="gtk-cancel":0 $YADBARS --title="$TITLE" --text="$TEXT" --window-icon="$ICON" --image="$IMAGE"

# ↑ launch yad multi progress-bar window
